name: Node.js CI/CD

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js 18.16.0
      uses: actions/setup-node@v2
      with:
        node-version: 18.16.0

    - name: Install Dependencies
      run: npm ci

    - name: Build
      run: npx tsc -p tsconfig.json

    - name: Build Docker Image
      run: |
        docker build -t burlive .
        
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push Docker Image
      run: |
        docker tag burlive:latest ${{ secrets.DOCKER_USERNAME }}/burlive:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/burlive:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Deploy to remote server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          docker pull ${{ secrets.DOCKER_USERNAME }}/burlive:latest
          docker stop burlive || true
          docker rm burlive || true
          docker rmi ${{ secrets.DOCKER_USERNAME }}/burlive:current || true
          docker tag ${{ secrets.DOCKER_USERNAME }}/burlive:latest ${{ secrets.DOCKER_USERNAME }}/burlive:current
          docker run -d --name burlive -p 5000:5000 -v /opt/burlive/ssl:/app/ssl --env-file /opt/burlive/.env ${{ secrets.DOCKER_USERNAME }}/burlive:current
          
    - name: Update code on server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          cd /opt/burlive
          git pull
